### ISSUE TITLE
Alignment with human right violations

### ISSUE THREAD

**Issue by WardPearce** [interaapps/pastefy#57]
https://www.hrw.org/report/2021/04/27/threshold-crossed/israeli-authorities-and-crimes-apartheid-and-persecution

**Comment by Nakilon** [comment]
🤡

**Comment by JulianFun123** [comment]
Calling israel an apartheid-regime does not only play down the crimes made in Douth Africa and is because of its unbalanced calling antisemitic (https://www.adl.org/resources/backgrounder/allegation-israel-apartheid-state) (especially in times where the innocent civilians get murdered). 
It has nothing to do with this Github project because it is a specific option set on the public pastefy instance and not in the Pastefy project.

This is why I will close this issue.

**Comment by WardPearce** [comment]
> Calling israel an apartheid-regime does not only play down the crimes made in Douth Africa and is because of its unbalanced calling antisemitic (https://www.adl.org/resources/backgrounder/allegation-israel-apartheid-state) (especially in times where the innocent civilians get murdered). It has nothing to do with this Github project because it is a specific option set on the public pastefy instance and not in the Pastefy project.
> 
> This is why I will close this issue.

The statement should be updated to condemn the crimes committed by Israel and Hamas. As both have killed civilians aimlessly.

The article you linked miss characterises the use apartheid, Palestine is very much facing system of racial segregation and oppression, it has nothing to do with classifying Jewish people as a race (what I would disagree with)

https://www.amnesty.org/en/latest/campaigns/2022/02/israels-system-of-apartheid/

Hopefully you side anti violence & anti war crimes, but thats up to you.

**Comment by JulianFun123** [comment]
Sorry, but this Amnesty International report is highly critized because of its anti-israeli bias https://en.wikipedia.org/wiki/Criticism_of_Amnesty_International#Israel, https://www.swp-berlin.org/publikation/amnesty-international-and-the-apartheid-claim-against-israel, https://www.europarl.europa.eu/doceo/document/E-9-2022-000932_EN.html, https://www.ngo-monitor.org/reports/amnesty-apartheid-analysis/, https://www.politico.eu/article/jewish-organizations-amnesty-international-uk-apartheid-israel-palestina/, https://www.zeit.de/2022/31/amnesty-international-antisemitismus-israel (Google translate required)

The terror is made by the Hamas. And yes: the Palestinian people are  also suffering. Mainly because of the hamas. And in times where Israel is being attacked by terrorist, we should all condemn the attacks rather than having a discussion about the past which has nothing to do with current events. This attack is not about the liberation of Palestine, it's about terrorizing jewish people and following the interests of the Iranian regime. And yes, I am anti violence and war crimes. Also made by Israel. Like the settlement policy. But seeing the current terrorist events as an acceptable response is not okay. We should first stand against and eliminate the Hamas and then have based discussion about how to end the problems.

**Comment by Nakilon** [comment]
You better now all admit what is the real war on the example of Israel/HAMAS after 1.5 years spent claiming that there is a "war between Ukraine and Russia, not SMO" and backtrack false claims, fakes, nazi hate propaganda polluttion from all over the GitHub. Oh, I forgot, no one has apologized for 8 years of claims that "there is Russian army in Ukraine" after only in 2022 the actual army came in. Apologize not for me but for my relatives, my family living there all this time. And for sanctions that apply not against Russia but first of all against the actual locals, such as Crimeans, punishing them for standing for their rights to be protected.

**Comment by JulianFun123** [comment]
Russia is attacking Ukraine. Get the facts right. I am sorry for your family that they are under the terror by the Russian regime. The sanctions are there to lead you to remove your murdering dictator Putin.

**Comment by WardPearce** [comment]
for a bit of context around how Israel isn't just killing Humus

![ABoringDystopia-17mv40h](https://github.com/interaapps/pastefy/assets/27844174/34299c76-ffae-4093-9497-a49c73391cec)
